name: GriefPrevention
main: me.ryanhamshire.GriefPrevention.GriefPrevention
softdepend: [Multiverse-Core, My_Worlds, MystCraft, Transporter, RoyalCommands, MultiWorld, Denizen, CommandHelper]
dev-url: https://dev.bukkit.org/projects/grief-prevention
version: '${git.commit.id.describe}'
api-version: '1.20'
commands:
    abandonclaim:
      description: Deletes a claim.
      usage: /<command>
      aliases: [unclaim, declaim, removeclaim, disclaim]
      permission: griefprevention.abandonclaim
    abandontoplevelclaim:
      description: Deletes a claim and all its subdivisions.
      usage: /<command>
      permission: griefprevention.abandontoplevelclaim
    abandonallclaims:
      description: Deletes ALL your claims.
      usage: /<command>
      permission: griefprevention.abandonallclaims
    trust:
      description: Grants a player full access to your claim(s).
      usage: /<command> <player>  Grants a player permission to build.  See also /untrust, /containertrust, /accesstrust, and /permissiontrust.
      aliases: tr
      permission: griefprevention.trust
    untrust:
      description: Revokes a player's access to your claim(s).
      usage: /<command> <player>
      aliases: ut
      permission: griefprevention.untrust
    containertrust:
      description: Grants a player access to your claim's containers, crops, animals, bed, buttons, and levers.
      usage: /<command> <player>.  Grants a player access to your inventory, crops, animals, bed, and buttons/levers.
      aliases: ct
      permission: griefprevention.containertrust
    accesstrust:
      description: Grants a player entry to your claim(s) and use of your bed, buttons, and levers.
      usage: /<command> <player>.  Grants a player access to your bed, buttons, and levers.
      aliases: at
      permission: griefprevention.accesstrust
    permissiontrust:
      description: Grants a player permission to manage the claim trustlist.
      usage: /<command> <player>.  Permits a player to /trust and /untrust players in the claim.
      aliases: [pt, managetrust]
      permission: griefprevention.permissiontrust
    subdivideclaims:
      description: Switches the shovel tool to subdivision mode, used to subdivide your claims.
      usage: /<command>
      aliases: [sc, subdivideclaim]
      permission: griefprevention.subdivideclaims
    restrictsubclaim:
      description: Restricts a subclaim, so that it inherits no permissions from the parent claim
      usage: /<command>
      aliases: rsc
      permission: griefprevention.restrictsubclaim
    adjustbonusclaimblocks:
      description: Adds or subtracts bonus claim blocks for a player.
      usage: /<command> <player> <amount>
      permission: griefprevention.adjustbonusclaimblocks
      aliases: acb
    adjustbonusclaimblocksall:
      description: Adds or subtracts bonus claim blocks for all online players.
      usage: /<command> <amount>
      permission: griefprevention.adjustbonusclaimblocksall
      aliases: acball
    setaccruedclaimblocks:
      description: Updates a player's accrued claim block total.
      usage: /<command> <player> <amount>
      permission: griefprevention.setaccruedclaimblocks
      aliases: scb
    deleteclaim:
      description: Deletes the claim you're standing in, even if it's not your claim.
      usage: /<command>
      permission: griefprevention.deleteclaim
    deleteallclaims:
      description: Deletes all of another player's claims.
      usage: /<command> <player>
      permission: griefprevention.deleteallclaims
    deleteclaimsinworld:
      description: Deletes all the claims in a world.  Only usable at the server console.
      usage: /<command> <world>
      aliases: [deleteallclaimsinworld, clearclaimsinworld, clearallclaimsinworld]
      permission: griefprevention.deleteclaimsinworld
    deleteuserclaimsinworld:
      description: Deletes all the non-admin claims in a world.  Only usable at the server console.
      usage: /<command> <world>
      aliases: [deletealluserclaimsinworld, clearuserclaimsinworld, clearalluserclaimsinworld]
      permission: griefprevention.deleteuserclaimsinworld
    adminclaims:
      description: Switches the shovel tool to administrative claims mode.
      usage: /<command>
      permission: griefprevention.adminclaims
      aliases: ac
    basicclaims:
      description: Switches the shovel tool back to basic claims mode.
      usage: /<command>
      aliases: bc
      permission: griefprevention.basicclaims
    extendclaim:
      description: Resizes the land claim you're standing in by pushing or pulling its boundary in the direction you're facing.
      usage: /<command> <numberOfBlocks>
      aliases: [expandclaim, resizeclaim]
      permission: griefprevention.extendclaim
    claim:
      description: Creates a land claim centered at your current location.
      usage: /<command> [optional radius]
      aliases: [createclaim, makeclaim, newclaim]
      permission: griefprevention.claim
    trapped:
      description: Ejects you to nearby unclaimed land.  Has a substantial cooldown period.
      usage: /<command>
      permission: griefprevention.trapped
    trustlist:
      description: Lists permissions for the claim you're standing in.
      usage: /<command>
      permission: griefprevention.trustlist
    ignoreclaims:
      description: Toggles ignore claims mode.
      usage: /<command>
      permission: griefprevention.ignoreclaims
      aliases: ic
    deletealladminclaims:
      description: Deletes all administrative claims. Only usable at the server console.
      usage: /<command>
      permission: griefprevention.deletealladminclaims
    adminclaimslist:
      description: Lists all administrative claims.
      usage: /<command>
      permission: griefprevention.adminclaims
    transferclaim:
      description: Converts an administrative claim to a private claim.
      usage: /<command> <player>
      aliases: giveclaim
      permission: griefprevention.transferclaim
    unlockdrops:
      description: Allows other players to pick up the items you dropped when you died.
      usage: /<command>
      permission: griefprevention.unlockdrops
    claimslist:
      description: Lists information about a player's claim blocks and claims.
      usage: /<command> or /<command> <player>
      aliases: [claimlist, listclaims]
      permission: griefprevention.claimslist
    claimexplosions:
      description: Toggles whether explosives may be used in a specific land claim.
      usage: /<command>
      permission: griefprevention.claimexplosions
      aliases: claimexplosion
    softmute:
      description: Toggles whether a player's messages will only reach other soft-muted players.
      usage: /<command> <player>
      permission: griefprevention.softmute
    gpreload:
      description: Reloads Grief Prevention's configuration settings.  Does NOT totally reload the entire plugin.
      usage: /<command>
      permission: griefprevention.reload
    ignoreplayer:
      description: Ignores another player's chat messages.
      usage: /<command> <player name>
      aliases: [ignore]
      permission: griefprevention.ignoreplayer
    unignoreplayer:
      description: Unignores another player's chat messages.
      usage: /<command> <player name>
      aliases: [unignore]
      permission: griefprevention.unignoreplayer
    ignoredplayerlist:
      description: Lists the players you're ignoring in chat.
      usage: /<command>
      aliases: [ignores, ignored, ignorelist, ignoredlist, listignores, listignored, ignoring]
      permission: griefprevention.ignoredplayerlist
    separate:
      description: Forces two players to ignore each other in chat.
      usage: /<command> <player1> <player2>
      permission: griefprevention.separateplayer
    unseparate:
      description: Reverses /separate.
      usage: /<command> <player1> <player2>
      permission: griefprevention.unseparateplayer
    claimbook:
      description: Gives a player a manual about claiming land.
      usage: /<command> <player>
      permission: griefprevention.claimbook
permissions:
    griefprevention.createclaims:
        description: Grants permission to create claims.
        default: true
    griefprevention.admin.*:
        description: Grants all administrative functionality.
        children:
            griefprevention.ignoreclaims: true
            griefprevention.adminclaims: true
            griefprevention.adminclaimslist: true
            griefprevention.adjustclaimblocks: true
            griefprevention.deleteclaims: true
            griefprevention.spam: true
            griefprevention.lava: true
            griefprevention.eavesdrop: true
            griefprevention.deathblow: true
            griefprevention.softmute: true
            griefprevention.reload: true
            griefprevention.visualizenearbyclaims: true
            griefprevention.overrideclaimcountlimit: true
            griefprevention.transferclaim: true
            griefprevention.claimslistother: true
            griefprevention.separate: true
            griefprevention.unseparate: true
            griefprevention.eavesdropsigns: true
            griefprevention.claimbook: true
            griefprevention.notignorable: true
            griefprevention.seeinactivity: true
            griefprevention.eavesdropimmune: true
            griefprevention.deleteclaimsinworld: true
            griefprevention.deleteuserclaimsinworld: true
            griefprevention.deletealladminclaims: true
            griefprevention.unlockothersdrops: true
            griefprevention.seeclaimsize: true
    griefprevention.extendclaim.toolbypass:
        description: Allows a player to extend a claim without a modification tool.
        default: false
    griefprevention.unlockdrops:
        description: Grants permission to use /unlockdrops.
        default: true
    griefprevention.unlockothersdrops:
        description: Grants permission to use /unlockdrops for other players.
        default: op
    griefprevention.trapped:
        description: Grants permission to use /trapped.
        default: true
    griefprevention.claimslistother:
        description: Grants permission to use /claimslist to get another player's information.
        default: op
    griefprevention.transferclaim:
        description: Grants permission to use /transferclaim.
        default: op
    griefprevention.ignoreclaims:
        description: Grants permission to use /ignoreclaims.
        default: op
    griefprevention.adminclaims:
        description: Grants permission to create administrative claims.
        default: op
    griefprevention.adminclaimslist:
      description: Grants permission to list administrative claims.
      default: op
    griefprevention.deleteclaims:
        description: Grants permission to delete other players' claims.
        default: op
        children:
          griefprevention.deleteclaim: true
          griefprevention.deleteallclaims: true
    griefprevention.adjustclaimblocks:
        description: Grants permission to add or remove bonus blocks from a player's account.
        default: op
        children:
          griefprevention.adjustbonusclaimblocks: true
          griefprevention.adjustbonusclaimblocksall: true
          griefprevention.setaccruedclaimblocks: true
    griefprevention.spam:
        description: Grants permission to log in, send messages, and send commands rapidly.
        default: op
    griefprevention.lava:
        description: Grants permission to place lava near the surface and outside of claims.
        default: op
    griefprevention.eavesdrop:
        description: Allows a player to see whispered chat messages (/tell) and softmuted messages.
        default: op
    griefprevention.eavesdropsigns:
        description: Allows a player to see sign placements as chat messages.
        default: op
    griefprevention.reload:
        description: Grants access to /gpreload.
        default: op
    griefprevention.softmute:
        description: Grants access to /softmute.
        default: op
    griefprevention.claims:
        description: Grants access to claim-related slash commands.
        default: true
        children:
          griefprevention.abandonclaim: true
          griefprevention.abandontoplevelclaim: true
          griefprevention.trust: true
          griefprevention.untrust: true
          griefprevention.containertrust: true
          griefprevention.accesstrust: true
          griefprevention.permissiontrust: true
          griefprevention.subdivideclaims: true
          griefprevention.restrictsubclaim: true
          griefprevention.basicclaims: true
          griefprevention.extendclaim: true
          griefprevention.claim: true
          griefprevention.trustlist: true
          griefprevention.claimslist: true
          griefprevention.claimexplosions: true
    griefprevention.abandonallclaims:
        description: Grants access to /abandonallclaims.
        default: true
    griefprevention.visualizenearbyclaims:
        description: Allows a player to see all nearby claims at once.
        default: op
    griefprevention.seeclaimsize:
        description: Allows a player to see claim size for other players claims when right clicking with investigation tool
        default: op
    griefprevention.overrideclaimcountlimit:
        description: Allows players to create more claims than the limit specified by the config.
        default: op
    griefprevention.separate:
        description: Grants access to /separate and /unseparate.
        default: op
        children:
          griefprevention.separateplayer: true
          griefprevention.unseparateplayer: true
    griefprevention.ignore:
        description: Grants access to /ignore, /unignore, and /ignorelist
        default: true
        children:
          griefprevention.ignoreplayer: true
          griefprevention.unignoreplayer: true
          griefprevention.ignoredplayerlist: true
    griefprevention.claimbook:
        description: Grants access to /claimbook.
        default: op
    griefprevention.notignorable:
        description: Players with this permission can't be ignored.
        default: op
    griefprevention.seeinactivity:
        description: Players with this permission can see how long a claim owner has been offline.
        default: op
    griefprevention.eavesdropimmune:
        description: Players with this permission can't have their private messages eavesdropped.
        default: op
    griefprevention.premovementchat:
        description: Players with this permission can chat before moving.
        default: false
